# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# site        网站          
title: LDQ的博客         #网站
subtitle: 前端              #网站副标题
description: 热爱前端     
#网站描述,给搜索引擎用的，在生成html中的head->meta中可看到
author: ldq              #作者
language: zh-Hans             #语言
timezone:                   #网站时区

# URL         网址
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
## 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，则请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
url: https://LDQ-first.github.io            #网址
root: /                                     #网站根目录
permalink: :year/:month/:day/:title/        #文章的永久链接格式
permalink_defaults:                         #永久链接中各部分的默认值

# Directory   目录
source_dir: source         #资源文件夹，这个文件夹用来存放内容。
public_dir: public         #公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags              #标签文件夹
archive_dir: archives      #归档文件夹
category_dir: categories   #分类文件夹
code_dir: downloads/code   #Include code 文件夹
i18n_dir: :lang            #国际化（i18n）文件夹
skip_render:               #跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。

# Writing     文章
new_post_name: :title.md # File name of new posts 新文章的文件名称
default_layout: post     # 预设布局
titlecase: false         # Transform title into titlecase 把标题转换为 title case
external_link: true      # Open external links in new tab 在新标签中打开链接
filename_case: 0         # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false     # 显示草稿
post_asset_folder: false  # 启动 Asset 文件夹
relative_link: false     # 把链接改为与根目录的相对位址
future: true             # 显示未来的文章
highlight:               # 代码块的设置,代码高亮
  enable: true           
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag   分类 & 标签
default_category: uncategorized    # 默认分类
category_map:                      # 分类别名
tag_map:                           # 标签别名

# Date / Time format   日期 / 时间格式
## Hexo uses Moment.js to parse and display date
## Hexo 使用 Moment.js 来解析和显示时间。
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD     # 日期格式
time_format: HH:mm:ss       # 时间格式

# Pagination        分页
## Set per_page to 0 to disable pagination
per_page: 10                #  每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page        #  分页目录

# Extensions    扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yelee             #当前主题名称。值为false时禁用主题

# Deployment    部署
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:LDQ-first/LDQ-first.github.io.git,master 
    coding: git@git.coding.net:LDQ-first/LDQ-first.coding.me.git,master  
  #branch: master

